"""Add sync_job_runs table

Revision ID: 2de76a87028a
Revises: d1e2f3a4b5c6
Create Date: 2026-04-21 19:05:36.580978
"""
from alembic import op
import sqlalchemy as sa



revision = '2de76a87028a'
down_revision = 'd1e2f3a4b5c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_stocks', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('partial_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_job_runs_job_name'), 'sync_job_runs', ['job_name'], unique=False)
    op.drop_index(op.f('idx_chat_traces_session_created_at'), table_name='chat_traces')
    op.drop_index(op.f('idx_chat_traces_user_created_at'), table_name='chat_traces')
    op.drop_index(op.f('idx_kap_report_chunking_status'), table_name='kap_reports')
    op.drop_index(op.f('idx_kap_report_pdf_download_status'), table_name='kap_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_kap_report_pdf_download_status'), 'kap_reports', ['pdf_download_status'], unique=False)
    op.create_index(op.f('idx_kap_report_chunking_status'), 'kap_reports', ['chunking_status'], unique=False)
    op.create_index(op.f('idx_chat_traces_user_created_at'), 'chat_traces', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_chat_traces_session_created_at'), 'chat_traces', ['session_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_sync_job_runs_job_name'), table_name='sync_job_runs')
    op.drop_table('sync_job_runs')
    # ### end Alembic commands ###
